### ISSUE TITLE
Circle doesn't get deleted

### ISSUE THREAD

**Issue by KohlerL-Smns** [GeekLaunch/button-ripple-effect#1]
The circle element isn't deleted after the animation. I would suggest to add:
`setTimeout(function() {
    circle.remove();
}, 600);`
at the bottom of 'createRipple' for a cleaner html after the animation.

**Comment by encody** [comment]
Thanks for the suggestion, but I addressed this in the video, and I'd prefer to keep the code in this repo the same as what was covered in the video. Feel free to fork this repo and make the change yourself, though!
